### PR TITLE
Sort clusters in left navigation by name

### LINKED ISSUE #43: Sort the cluster list by alpha
Sort the cluster list on the left nav by alphabetical.

### PR DESCRIPTION
**Pull request by paultannenbaum**
Fixes #43 
- Created an application controller and put sorting logic inside. This is where I felt was the best place for this logic, as controllers are basically meant to decorate templates for visual logic that the model is not concerned with.

Question: Should any other kind of lists (Bucket Types, Buckets, Keys, etc.) be sorted by name?

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
While I agree that controllers were created to decorate templates / do visual logic, I think the alpha-sorting should be moved into the store/service layer, because:
- Ember is moving away from controllers in general
- We never _not_ want to have the cluster list alphabetized. In fact, maybe we should just request it to be sorted on the server side..

**Comment by paultannenbaum** [comment]
Since we don't have a getAllClusters service in the explorer service, alpha sorting on clusters has to take place in the serializer. I think this is actually the correct place for it to happen as well. The explorer service is already taking care of a lot (fetching records, setting models), so adding additional logic feels like the service is taking on too much responsibilities. Moved alpha-sorting for bucket-types and nodes to serializers as well.

**Comment by paultannenbaum** [comment]
@dmitrizagidulin Do you like this solution or should we just update the service urls to have the sort params that @drewkerrigan added? Or have both?

**Comment by dmitrizagidulin** [comment]
Tested, looks great. +1 here.

(We'll go with the client-side sorting for the moment, until (or depending on whether) the server-side sorting is added).

**Pull request merged**
