### PR TITLE
Enforce space before parenthesis on table creation statement

### PR DESCRIPTION
**Pull request by paultannenbaum**
Fixes https://github.com/basho-labs/riak_explorer/issues/148
- Enforces a space before the first parenthesis in a table creation statement

### CODE REVIEW

**Comment by randysecrist** [comment]
This seems odd that the client has to do this to the query.  Does the query get passed directly to Riak TS and it barfs?

**Comment by paultannenbaum** [comment]
Yeah, that's exactly what was happening. I agree client side is probably not the best place to handle this, but its where I could step in and help out, especially since Drew is gone and not one is actively maintaining the erlang side of this application.

**Comment by travisbhartwell** [comment]
If we need something modified on the backend, I could probably look into it in a couple weeks once current priorities ramp down.

**Comment by paultannenbaum** [comment]
Thanks @travisbhartwell. Def ping me if you do get around to it, as I have spent quite a bit of time around this piece and can let you know whats happening on the client, and we can decide what should stay and what should move to the backend.

**Pull request merged**
